CREATE DATABASE doingsdone
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;
CREATE TABLE projects (
 id INT AUTO_INCREMENT PRIMARY_KEY,
 name CHAR(64)
);
CREATE TABLE tasks (
 id INT AUTO_INCREMENT PRIMARY_KEY,
 сreat_dt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 comp_dt TIMESTAMP,
 status INT DEFAULT 0 CHECK (status=0 and status=1),
 name CHAR(64),
 file CHAR(256),
 exp_dt TIMESTAMP
);
CREATE TABLE users (
 id INT AUTO_INCREMENT PRIMARY_KEY,
 reg_dt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 email CHAR(64) NOT NULL,
 usr_name CHAR(128),
 usr_pass CHAR(64)
);
